services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 7000:7000
    volumes:
      - ./frontend:/app
    networks:
      - oceanset_nework
    command: npm run dev -- --port 7000

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - oceanset_nework
    command: ["gunicorn", "-c", "./gunicorn/gunicorn.config.py", "wsgi:app"]

  nginx:
    extends:
      file: ./nginx/service.yml
      service: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - oceanset_nework

    depends_on:
      - frontend
      - backend

networks:
  oceanset_nework:
    name: oceanset_nework
